# When anything is pushed, install tree-sitter and run the command `tree-sitter generate && tree-sitter test` in the root directory of the repository.
name: Tree-sitter Test
on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libtree-sitter-dev

    - name: Install Tree-sitter
      run: |
        git clone https://github.com/tree-sitter/tree-sitter.git
        cd tree-sitter
        make
        sudo make install

    - name: Generate and Test
      run: |
        /usr/local/tree-sitter generate
        /usr/local/tree-sitter test
